// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEmnNZVx6InrpgbQGxd-gb57r1JkVlXfI',
    appId: '1:846702660282:web:748659e11547d28a559083',
    messagingSenderId: '846702660282',
    projectId: 'babytracker-9474d',
    authDomain: 'babytracker-9474d.firebaseapp.com',
    storageBucket: 'babytracker-9474d.firebasestorage.app',
    measurementId: 'G-W7H20W13BW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQoxOlczEITdnSOIRAcB9C2ZFq7tbBUSY',
    appId: '1:846702660282:android:dd03c9c21151df92559083',
    messagingSenderId: '846702660282',
    projectId: 'babytracker-9474d',
    storageBucket: 'babytracker-9474d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDofB9h3zh6Vy0r-513do48X4DUOLZgRpw',
    appId: '1:846702660282:ios:790cd5bdbb59f496559083',
    messagingSenderId: '846702660282',
    projectId: 'babytracker-9474d',
    storageBucket: 'babytracker-9474d.firebasestorage.app',
    iosBundleId: 'com.example.ios',
  );
}
